export const COURSES_LIST_REQUEST = "COURSES_LIST_REQUEST";
export const COURSES_LIST_SUCCESS = "COURSES_LIST_SUCCESS";
export const COURSES_LIST_FAIL = "COURSES_LIST_FAIL";

export const BLOCKEDCOURSES_LIST_REQUEST = "BLOCKEDCOURSES_LIST_REQUEST";
export const BLOCKEDCOURSES_LIST_SUCCESS = "BLOCKEDCOURSES_LIST_SUCCESS";
export const BLOCKEDCOURSES_LIST_FAIL = "BLOCKEDCOURSES_LIST_FAIL";

export const COURSES_CREATE_REQUEST = "COURSES_CREATE_REQUEST";
export const COURSES_CREATE_SUCCESS = "COURSES_CREATE_SUCCESS";
export const COURSES_CREATE_FAIL = "COURSES_CREATE_FAIL";

export const COURSES_UPDATE_REQUEST = "COURSES_UPDATE_REQUEST";
export const COURSES_UPDATE_SUCCESS = "COURSES_UPDATE_SUCCESS";
export const COURSES_UPDATE_FAIL = "COURSES_UPDATE_FAIL";

export const COURSES_DELETE_REQUEST = "COURSES_DELETE_REQUEST";
export const COURSES_DELETE_SUCCESS = "COURSES_DELETE_SUCCESS";
export const COURSES_DELETE_FAIL = "COURSES_DELETE_FAIL";

export const COURSES_BLOCK_REQUEST = "COURSES_BLOCK_REQUEST";
export const COURSES_BLOCK_SUCCESS = "COURSES_BLOCK_SUCCESS";
export const COURSES_BLOCK_FAIL = "COURSES_BLOCK_FAIL";

export const MENTOR_COURSES_REQUEST = "MENTOR_COURSES_REQUEST";
export const MENTOR_COURSES_SUCCESS = "MENTOR_COURSES_SUCCESS";
export const MENTOR_COURSES_FAIL = "MENTOR_COURSES_FAIL";

export const COURSE_Published_REQUEST = "COURSE_Published_REQUEST";
export const COURSE_Published_SUCCESS = "COURSE_Published_SUCCESS";
export const COURSE_Published_FAIL = "COURSE_Published_FAIL";

export const Published_LIST_REQUEST = "Published_LIST_REQUEST";
export const Published_LIST_SUCCESS = "Published_LIST_SUCCESS";
export const Published_LIST_FAIL = "Published_LIST_FAIL";

