export const MYCOURSES_GET_REQUEST = "MYCOURSES_GET_REQUEST";
export const MYCOURSES_GET_SUCCESS = "MYCOURSES_GET_SUCCESS";
export const MYCOURSES_GET_FAIL = "MYCOURSES_GET_FAIL";

export const COURSES_ENROLL_REQUEST = "COURSES_ENROLL_REQUEST";
export const COURSES_ENROLL_SUCCESS = "COURSES_ENROLL_SUCCESS";
export const COURSES_ENROLL_FAIL = "COURSES_ENROLL_FAIL";

export const COURSES_COMPLETE_REQUEST = "COURSES_COMPLETE_REQUEST";
export const COURSES_COMPLETE_SUCCESS = "COURSES_COMPLETE_SUCCESS";
export const COURSES_COMPLETE_FAIL = "COURSES_COMPLETE_FAIL";

export const GET_COMPLETED_REQUEST = "GET_COMPLETED_REQUEST";
export const GET_COMPLETED_SUCCESS = "GET_COMPLETED_SUCCESS";
export const GET_COMPLETED_FAIL = "GET_COMPLETED_FAIL";

export const COLORS = {
    accepted: "#059669",
    rejected: "#B91C1C",
    pending: "#6366F1",
    interviewing: "#2563EB",
    total: "#D97706",
  };