export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const GET_USERPIC_REQUEST = "GET_USERPIC_REQUEST";
export const GET_USERPIC_SUCCESS = "GET_USERPIC_SUCCESS";
export const GET_USERPIC_FAIL = "GET_USERPIC_FAIL";

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";

export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAIL = "USER_LIST_FAIL";

export const BLOCKEDUSER_LIST_REQUEST = "BLOCKEDUSER_LIST_REQUEST";
export const BLOCKEDUSER_LIST_SUCCESS = "BLOCKEDUSER_LIST_SUCCESS";
export const BLOCKEDUSER_LIST_FAIL = "BLOCKEDUSER_LIST_FAIL";

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAIL = "USER_DELETE_FAIL";

export const USER_BLOCK_REQUEST = "USER_BLOCK_REQUEST";
export const USER_BLOCK_SUCCESS = "USER_BLOCK_SUCCESS";
export const USER_BLOCK_FAIL = "USER_BLOCK_FAIL";

export const MENTOR_LIST_REQUEST = "MENTOR_LIST_REQUEST";
export const MENTOR_LIST_SUCCESS = "MENTOR_LIST_SUCCESS";
export const MENTOR_LIST_FAIL = "MENTOR_LIST_FAIL";

export const BLOCKEDMENTOR_LIST_REQUEST = "BLOCKEDMENTOR_LIST_REQUEST";
export const BLOCKEDMENTOR_LIST_SUCCESS = "BLOCKEDMENTOR_LIST_SUCCESS";
export const BLOCKEDMENTOR_LIST_FAIL = "BLOCKEDMENTOR_LIST_FAIL";
